// languages.js
export const LANGUAGES = [
  { code: "arabic", name: "Arabic (العربية)" },
  { code: "bangla", name: "Bengali / Bangla (বাংলা)" },
  { code: "bosnian", name: "Bosnian (Bosanski)" },
  { code: "bosnian", name: "Bosnian (Bosanski)" },
  { code: "chinese", name: "Chinese (简体中文)" },
  { code: "french", name: "French (Français)" },
  { code: "japanese", name: "Japanese (日本語)" },
  { code: "spanish", name: "Spanish (Español)" },
  { code: "indonesian", name: "Indonesian (Bahasa Indonesia)" },
  { code: "persian", name: "Persian / Farsi (فارسی)" },
  { code: "malay", name: "Malay (Bahasa Melayu)" },
  { code: "russian", name: "Russian (Русский)" },
  { code: "turkish", name: "Turkish (Türkçe)" },
  { code: "urdu", name: "Urdu (اردو)" },
];

// languages.js
// export const LANGUAGES = [
//   { code: "afrikaans", name: "Afrikaans" },
//   { code: "albanian", name: "Albanian (Shqip)" },
//   { code: "amharic", name: "Amharic (አማርኛ)" },
//   { code: "arabic", name: "Arabic (العربية)" },
//   { code: "armenian", name: "Armenian (Հայերեն)" },
//   { code: "assamese", name: "Assamese (অসমীয়া)" },
//   { code: "azerbaijani", name: "Azerbaijani (Azərbaycan)" },
//   { code: "bambara", name: "Bambara (Bamanankan)" },
//   { code: "bashkir", name: "Bashkir (Башҡорт)" },
//   { code: "basque", name: "Basque (Euskara)" },
//   { code: "belarusian", name: "Belarusian (Беларуская)" },
//   { code: "bangla", name: "Bengali / Bangla (বাংলা)" },
//   { code: "bhojpuri", name: "Bhojpuri (भोजपुरी)" },
//   { code: "bosnian", name: "Bosnian (Bosanski)" },
//   { code: "bulgarian", name: "Bulgarian (Български)" },
//   { code: "burmese", name: "Burmese (မြန်မာ)" },
//   { code: "cantonese", name: "Cantonese (粵語)" },
//   { code: "catalan", name: "Catalan (Català)" },
//   { code: "cebuano", name: "Cebuano (Bisaya)" },
//   { code: "chhattisgarhi", name: "Chhattisgarhi (छत्तीसगढ़ी)" },
//   { code: "chinese_mandarin", name: "Chinese Mandarin (中文)" },
//   { code: "czech", name: "Czech (Čeština)" },
//   { code: "danish", name: "Danish (Dansk)" },
//   { code: "dutch", name: "Dutch (Nederlands)" },
//   { code: "english", name: "English" },
//   { code: "esperanto", name: "Esperanto" },
//   { code: "estonian", name: "Estonian (Eesti)" },
//   { code: "filipino", name: "Filipino / Tagalog" },
//   { code: "finnish", name: "Finnish (Suomi)" },
//   { code: "french", name: "French (Français)" },
//   { code: "fulani", name: "Fulani / Fula (Pulaar)" },
//   { code: "galician", name: "Galician (Galego)" },
//   { code: "georgian", name: "Georgian (ქართული)" },
//   { code: "german", name: "German (Deutsch)" },
//   { code: "greek", name: "Greek (Ελληνικά)" },
//   { code: "gujarati", name: "Gujarati (ગુજરાતી)" },
//   { code: "haitian_creole", name: "Haitian Creole (Kreyòl)" },
//   { code: "hausa", name: "Hausa" },
//   { code: "hebrew", name: "Hebrew (עברית)" },
//   { code: "hindi", name: "Hindi (हिन्दी)" },
//   { code: "hmong", name: "Hmong (Hmoob)" },
//   { code: "hungarian", name: "Hungarian (Magyar)" },
//   { code: "icelandic", name: "Icelandic (Íslenska)" },
//   { code: "igbo", name: "Igbo" },
//   { code: "indonesian", name: "Indonesian (Bahasa Indonesia)" },
//   { code: "irish", name: "Irish (Gaeilge)" },
//   { code: "italian", name: "Italian (Italiano)" },
//   { code: "japanese", name: "Japanese (日本語)" },
//   { code: "javanese", name: "Javanese (Basa Jawa)" },
//   { code: "kannada", name: "Kannada (ಕನ್ನಡ)" },
//   { code: "kazakh", name: "Kazakh (Қазақ)" },
//   { code: "khmer", name: "Khmer (ភាសាខ្មែរ)" },
//   { code: "kinyarwanda", name: "Kinyarwanda" },
//   { code: "korean", name: "Korean (한국어)" },
//   { code: "kurdish", name: "Kurdish (Kurdî)" },
//   { code: "kyrgyz", name: "Kyrgyz (Кыргызча)" },
//   { code: "lao", name: "Lao (ລາວ)" },
//   { code: "latvian", name: "Latvian (Latviešu)" },
//   { code: "lithuanian", name: "Lithuanian (Lietuvių)" },
//   { code: "macedonian", name: "Macedonian (Македонски)" },
//   { code: "maithili", name: "Maithili (मैथिली)" },
//   { code: "malagasy", name: "Malagasy" },
//   { code: "malay", name: "Malay (Bahasa Melayu)" },
//   { code: "malayalam", name: "Malayalam (മലയാളം)" },
//   { code: "marathi", name: "Marathi (मराठी)" },
//   { code: "mongolian", name: "Mongolian (Монгол)" },
//   { code: "nepali", name: "Nepali (नेपाली)" },
//   { code: "norwegian", name: "Norwegian (Norsk)" },
//   { code: "odia", name: "Odia (ଓଡ଼ିଆ)" },
//   { code: "oromo", name: "Oromo (Afaan Oromoo)" },
//   { code: "pashto", name: "Pashto (پښتو)" },
//   { code: "persian", name: "Persian / Farsi (فارسی)" },
//   { code: "polish", name: "Polish (Polski)" },
//   { code: "portuguese", name: "Portuguese (Português)" },
//   { code: "punjabi", name: "Punjabi (ਪੰਜਾਬੀ)" },
//   { code: "romanian", name: "Romanian (Română)" },
//   { code: "russian", name: "Russian (Русский)" },
//   { code: "saraiki", name: "Saraiki (سرائیکی)" },
//   { code: "serbian", name: "Serbian (Српски)" },
//   { code: "shona", name: "Shona (chiShona)" },
//   { code: "sindhi", name: "Sindhi (سنڌي)" },
//   { code: "sinhala", name: "Sinhala (සිංහල)" },
//   { code: "slovak", name: "Slovak (Slovenčina)" },
//   { code: "slovenian", name: "Slovenian (Slovenščina)" },
//   { code: "somali", name: "Somali (Soomaali)" },
//   { code: "spanish", name: "Spanish (Español)" },
//   { code: "sundanese", name: "Sundanese (Basa Sunda)" },
//   { code: "swahili", name: "Swahili (Kiswahili)" },
//   { code: "swedish", name: "Swedish (Svenska)" },
//   { code: "tamil", name: "Tamil (தமிழ்)" },
//   { code: "telugu", name: "Telugu (తెలుగు)" },
//   { code: "thai", name: "Thai (ไทย)" },
//   { code: "turkish", name: "Turkish (Türkçe)" },
//   { code: "ukrainian", name: "Ukrainian (Українська)" },
//   { code: "urdu", name: "Urdu (اردو)" },
//   { code: "uzbek", name: "Uzbek (Oʻzbek)" },
//   { code: "vietnamese", name: "Vietnamese (Tiếng Việt)" },
//   { code: "yoruba", name: "Yoruba (Yorùbá)" },
//   { code: "zulu", name: "Zulu (isiZulu)" }
// ];