export const PLACEHOLDER_TEXTS = {
  afrikaans: "Vra oor verse, Hadiths of temas...",
  albanian: "Pyetni rreth vargjeve, haditheve apo temave...",
  amharic: "ስለ አንቀጾች፣ ሐዲሶች ወይም ርዕሰ ጉዳዮች ጠይቅ...",
  arabic: "اسأل عن الآيات، الأحادیث، أو الموضوعات...",
  armenian: "Հարցրեք համարների, հադիսների կամ թեմաների մասին...",
  assamese: "আয়াত, হাদীচ বা বিষয়ৰ বিষয়ে সোধক...",
  azerbaijani: "Ayələr, hədislər və ya mövzular haqqında soruşun...",
  bambara: "Kibaarow, Hadisɛw walla kuluw kofɔ...",
  bashkir: "Аяттар, хәдистәр йәки темалар тураһында һорағыҙ...",
  basque: "Galdetu bertsoei, hadithei edo gaiei buruz...",
  belarusian: "Спытайце пра вершы, хадзісы або темы...",
  bangla: "আয়াত, হাদিস বা বিষয় সম্পর্কে জিজ্ঞাসা করুন...",
  bhojpuri: "आयात, हदीस चाहे बिषय के बारे में पूछीं...",
  bosnian: "Pitajte o ajetima, hadisima ili temama...",
  bulgarian: "Попитайте за знамения, хадиси или теми...",
  burmese: "အာယာတ်တော်များ၊ ဟဒီးစ်များ သို့မဟုတ် အကြောင်းအရာများအကြောင်း မေးမြန်းပါ...",
  cantonese: "查詢經文、 হাদীস (Hadith) 或主題...",
  catalan: "Pregunta sobre versets, hadits o temes...",
  cebuano: "Pangutana bahin sa mga bersikulo, hadith, o tema...",
  chhattisgarhi: "आयात, हदीस या बिषय मन के बारे मा पूछव...",
  chinese_mandarin: "询问经文、圣训或主题...",
  czech: "Zaptejte se na verše, hadísy nebo témata...",
  danish: "Spørg om vers, hadither eller emner...",
  dutch: "Vraag naar verzen, hadiths of thema's...",
  english: "Ask about verses, hadiths, or themes...",
  esperanto: "Demandu pri versoj, haditoj aŭ temoj...",
  estonian: "Küsige värsside, hadithide või teemade kohta...",
  filipino: "Magtanong tungkol sa mga talata, hadith, o paksa...",
  finnish: "Kysy jakeista, haditheista tai teemoista...",
  french: "Posez une question sur les versets, les hadiths ou les thèmes...",
  fulani: "Aamno ko faati e aayaaji, hadiisaaji walla toɓɓe...",
  galician: "Pregunta sobre versículos, hadiths ou temas...",
  georgian: "იשאითხეთ აიათების, ჰადისების ან თემების შესახებ...",
  german: "Fragen Sie nach Versen, Hadithen oder Themen...",
  greek: "Ρωτήστε για εδάφια, χαντίθ ή θέματα...",
  gujarati: "આયતો, હદીસો અથવા વિષયો વિશે પૂછો...",
  haitian_creole: "Mande sou vèsè, hadith, oswa tèm...",
  hausa: "Tambaya game da ayoyi, hadisai, ko batutuwa...",
  hebrew: "שאל על פסוקים, חדית'ים או נושאים...",
  hindi: "आयत, हदीस या विषयों के बारे में पूछें...",
  hmong: "Nroog txog cov nqe lus, hadiths, lossis cov ntsiab lus...",
  hungarian: "Kérdezzen az versekről, hadíszokról vagy témákról...",
  icelandic: "Spyrðu um vers, hadith eða efni...",
  igbo: "Jụọ maka amaokwu, hadiths, ma ọ bụ isiokwu...",
  indonesian: "Tanyakan tentang ayat, hadis, atau tema...",
  irish: "Fiafraigh faoi véarsaí, hadiths, nó téamaí...",
  italian: "Chiedi informazioni su versi, hadith o temi...",
  japanese: "句、ハディース、またはテーマについて質問する...",
  javanese: "Tatakon babagan ayat, hadis, utawa tema...",
  kannada: "ವಚನಗಳು, ಹದೀಸ್‌ಗಳು ಅಥವಾ ವಿಷಯಗಳ ගැන ಕೇಳಿ...",
  kazakh: "Аяттар, хадистер немесе тақырыптар туралы сұраңыз...",
  khmer: "សួរអំពីខគម្ពីរ ហាឌីត ឬប្រធានបទ...",
  kinyarwanda: "Baza ibyerekeye imirongo, hadithi, cyangwa insanganyamatsiko...",
  korean: "구절, 하디스, 주제에 대해 질문하세요...",
  kurdish: "Pirs li ser ayet, hedîs, an mijaran bikin...",
  kyrgyz: "Аяттар, хадистер же темалар жөнүндө сураңыз...",
  lao: "ຖາມກ່ຽວກັບຂໍ້ຄວາມ, ຮາດີດ, ຫຼື ຫົວຂໍ້...",
  latvian: "Jautājiet par pants, hadīsiem vai tēmām...",
  lithuanian: "Paklauskite apie posmus, hadisus ar temas...",
  macedonian: "Прашајте за стихови, хадиси или теми...",
  maithili: "आयात, हदीस या विषयक बारे में पूछू...",
  malagasy: "Manontania momba ny andininy, hadith, na lohahevitra...",
  malay: "Tanya tentang ayat, hadis, atau tema...",
  malayalam: "വചനങ്ങളെക്കുറിച്ചോ ഹദീസുകളെക്കുറിച്ചോ വിഷയങ്ങളെക്കുറിച്ചോ ചോദിക്കുക...",
  marathi: "आयती, हदीस किंवा विषयांबद्दल विचारा...",
  mongolian: "Бадаг, хадис эсвэл сэдвийн талаар асуугаарай...",
  nepali: "आयत, हदीस वा विषयहरूको बारेमा सोध्नुहोस्...",
  norwegian: "Spør om vers, hadither eller temaer...",
  odia: "ଆୟାତ, ହାଦିସ କିମ୍ବା ବିଷୟ ବିଷୟରେ ପଚାରନ୍ତୁ...",
  oromo: "Keeyyatoota, hadiisota, ykn mata dureewwan ilaalchisee gaafadhu...",
  pashto: "د آیتونو، حدیثونو یا موضوعګانو په اړه وپوښتئ...",
  persian: "درباره آیات، احادیث یا موضوعات بپرسید...",
  polish: "Zapytaj o wersety, hadisy lub tematy...",
  portuguese: "Pergunte sobre versículos, hadiths ou temas...",
  punjabi: "ਆਇਤਾਂ, ਹਦੀਸਾਂ ਜਾਂ ਵਿਸ਼ਿਆਂ ਬਾਰੇ ਪੁੱਛੋ...",
  romanian: "Întreabă despre versete, hadisuri sau teme...",
  russian: "Спросите об аятах, хадисах или темах...",
  saraiki: "آیات، حدیثاں یا موضوعات دے بارے وچ پوچھو...",
  serbian: "Питајте о ајетима, хадисима или темама...",
  shona: "Bvunza nezve ndima, hadith, kana misoro yenyaya...",
  sindhi: "آيتن، حديثن يا موضوعن بابت پڇو...",
  sinhala: "අයත්, හදීස් හෝ තේමාවන් ගැන අසන්න...",
  slovak: "Opýtajte sa na verše, hadísy alebo témy...",
  slovenian: "Vprašajte o verzih, hadisih ali temah...",
  somali: "Weydii Aayadaha, Xadiisyada, ama Mawduucyada...",
  spanish: "Pregunta sobre versículos, hadices o temas...",
  sundanese: "Tanya ngeunaan ayat, hadits, atawa téma...",
  swahili: "Uliza kuhusu aya, hadithi, au mada...",
  swedish: "Fråga om verser, hadither eller teman...",
  tamil: "வசனங்கள், ஹதீஸ்கள் அல்லது தீம்கள் பற்றி கேட்கவும்...",
  telugu: "వాక్యాలు, హదీసులు లేదా అంశాల గురించి అడగండి...",
  thai: "ถามเกี่ยวกับโองการ ฮะดีษ หรือหัวข้อ...",
  turkish: "Ayetler, hadisler veya konular hakkında soru sorun...",
  ukrainian: "Запитайте про аяти, хадиси или теми...",
  urdu: "آیات، احادیث، یا موضوعات کے بارے میں پوچھیں...",
  uzbek: "Oyatlar, hadislar yoki mavzular haqida so'rang...",
  vietnamese: "Hỏi về các câu kinh, hadith, hoặc chủ đề...",
  yoruba: "Beere nipa awon ese, hadis, tabi awon orieko...",
  zulu: "Buza ngamavesi, amagugu e-Hadith, noma izingqikithi..."
};